[[headers]]
  for = "/*"
  [headers.values]
    access-control-allow-origin = "https://www.unpkg.com"

[[redirects]]
  from = "/next/*"
  to = "https://main--lynx-doc.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/3.4/*"
  to = "/:splat"
  status = 302